name: PHP Composer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add PHP8 repository
        run: sudo apt -y install software-properties-common

      - name: Add PHP8 repository
        run: sudo add-apt-repository ppa:ondrej/php

      - name: Update
        run: sudo apt update

      - name: Init PHP Unit
        run: sudo apt install php8.x php8.x-cli php8.x-common php8.x-mbstring php8.x-xml php8.x-mysql php8.x-curl php8.x-gd

      - name: Init PHP Unit
        run: composer require --dev phpunit/phpunit ^11

      - name: PHP Unit check version
        run: ./vendor/bin/phpunit --version

      - name: Run PHP Unit
        run: ./vendor/bin/phpunit tests
